### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by wzylove** [mandalinadagi/WGSR#1]
![image](https://github.com/mandalinadagi/WGSR/assets/153968555/6bf02a13-efe0-45dd-b23a-286bab9c7f81)
Thanks to the author's work, during the training process, spectral_norm was missing.

**Comment by mandalinadagi** [comment]
thank you for pointing out, spectral_norm.py is added under codes/models/modules [folder](https://github.com/mandalinadagi/WGSR/blob/main/codes/models/modules/spectral_norm.py). Please let us know if there is any other problem during the training
