### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by wzylove** [mandalinadagi/WGSR#2]
![image](https://github.com/mandalinadagi/WGSR/assets/153968555/35a2faf8-4c08-466d-98c4-3f2b010952e4)
Thanks to the author for his reply last night. There is no problem with this spectral_norm, but there seems to be a new problem. As shown in the picture, this thing seems to be missing.

**Comment by mandalinadagi** [comment]
Sorry for the missing file, it is added to the repository. In order to not to encounter any problems training codes are tested and bugs are fixed now. Thanks
