### ISSUE TITLE
Metrics and validation images

### ISSUE THREAD

**Issue by WeiYangHui** [mandalinadagi/WGSR#6]
Hi，dear authors. Could you provice the metric files that you measure in the paper?
Or please provide the validation images of DIV2K, thanks very much.

**Comment by mandalinadagi** [comment]
As requested, DIV2K results are added to Google Drive, you can download from here: https://drive.google.com/drive/folders/19Ur1SF-49erDA8fOoZAx1_Pnt7ZKRT0X

**Comment by WeiYangHui** [comment]
Thanks very much.
